a=open("modified_enwik9", 'r', encoding='utf-8').read()
a=a.replace("  ","")
print(1)
a=a.replace("<page>","<p")
print(2)
a=a.replace("</page>","/p")
print(3)
a=a.replace("<title>","<l")
print(4)
a=a.replace("</title>","/l")
print(5)
a=a.replace("<id>","<d")
print(6)
a=a.replace("</id>","/d")
print(7)
a=a.replace("<timestamp>","<i")
print(8)
a=a.replace("</timestamp>","/i")
print(9)
a=a.replace("<revision>","<r")
print(10)
a=a.replace("</revision>","/r")
print(11)
a=a.replace("<contributor>","<c")
print(12)
a=a.replace("</contributor>","/c")
print(13)
a=a.replace("<username>","<u")
print(14)
a=a.replace("</username>","/u")
print(15)
a=a.replace('<text xml:space="preserve">',"<tx")
print(16)
a=a.replace("</text>","/t")
print(17)
a=a.replace("<text","<t")
print(18)
a=a.replace("<minor","<m")
print(19)
a=a.replace("<comment>","c")
print(20)
a=a.replace("</comment>","/c")
print(21)
a=a.replace("REDIRECT","r")
print(22)
a=a.replace("https","s")
print(23)
a=a.replace("http","")
print(24)
a=a.replace("<ip>","<e")
print(25)
a=a.replace("</ip>","/e")
print(26)
a=a.replace(" the "," t ")
print(27)
a=a.replace(" of "," o ")
print(28)
a=a.replace(" and "," n ")
print(29)
a=a.replace(" in "," i ")
print(30)
a=a.replace(" to "," f ")
print(31)
a=a.replace(" a ","A")
print(32)
a=a.replace(" is ","I")
print(33)
a=a.replace(" for "," r ")
print(34)
a=a.replace(" are "," e ")
print(35)
a=a.replace(" was "," w ")
print(36)
a=a.replace(" The ","T")
print(37)
a=a.replace(" as "," s ")
print(38)
a=a.replace(" by ","N")
print(39)
a=a.replace(" with ","O")
print(40)
a=a.replace(" from ","P")
print(41)
a=a.replace(" that ","B")
print(42)
a=a.replace(" on ","R")
print(43)
a=a.replace(" - ","S")
print(44)
a=a.replace(" or ","U")
print(45)
a=a.replace(" at ","E")
print(46)
a=a.replace(" an ","F")
print(47)
a=a.replace(" his ","H")
print(48)
a=a.replace(" have ","L")
print(49)
a=a.replace(" it ","M")
print(50)
a=a.replace(" which ","1")
print(51)
a=a.replace(" be ","2")
print(52)
a=a.replace(" (U.S. ","3")
print(53)
a=a.replace(" age ","4")
print(54)
a=a.replace(" he ","5")
print(55)
a=a.replace(" has ","6")
print(56)
a=a.replace(" were ","7")
print(57)
a=a.replace(" not ","8")
print(58)
a=a.replace(" also ","9")
print(59)
a=a.replace(" who ","!")
print(60)
a=a.replace(" had ","@")
print(61)
a=a.replace(" this ","#")
print(62)
a=a.replace(" but ","$")
print(63)
a=a.replace(" = ","%")
print(64)
a=a.replace(" | ","^")
print(65)
a=a.replace(" their ","&")
print(66)
a=a.replace(" there ","*")
print(67)
a=a.replace(" In ","(")
print(68)
a=a.replace(" under ",")")
print(69)
a=a.replace(" one ","+")
print(70)
a=a.replace(" more ","~")
print(71)
a=a.replace(" population ","`")
print(72)
b=open("a","w", encoding='utf-8')
b.write(a)
b.close()
