enwik9=open("modified_enwik9", 'r', encoding='utf-8').read()
e=enwik9
e=e.replace("<page>","")
e=e.replace("</page>","")
e=e.replace("<title>","")
e=e.replace("</title>","")
e=e.replace("<id>","")
e=e.replace("</id>","")
e=e.replace("<ip>","")
e=e.replace("</ip>","")
e=e.replace("<revision>","")
e=e.replace("</revision>","")
e=e.replace("<timestamp>","")
e=e.replace("</timestamp>","")
e=e.replace("<contributor>","")
e=e.replace("</contributor>","")
e=e.replace("<username>","")
e=e.replace("</username>","")
e=e.replace("<comment>","")
e=e.replace("</comment>","")
f=open("a","w", encoding='utf-8')
f.write(e)
f.close() 