a=open("modified_enwik9", 'r', encoding='utf-8').read()
a=a.replace("  ","")
print(1)
a=a.replace("<page>","")
print(2)
a=a.replace("</page>","")
print(3)
a=a.replace("<title>","")
print(4)
a=a.replace("</title>","")
print(5)
a=a.replace("<id>","")
print(6)
a=a.replace("</id>","")
print(7)
a=a.replace("<timestamp>","")
print(8)
a=a.replace("</timestamp>","")
print(9)
a=a.replace("<revision>","")
print(10)
a=a.replace("</revision>","")
print(11)
a=a.replace("<contributor>","")
print(12)
a=a.replace("</contributor>","")
print(13)
a=a.replace("<username>","")
print(14)
a=a.replace("</username>","")
print(15)
a=a.replace('<text xml:space="preserve">',"x")
print(16)
a=a.replace("</text>","")
print(17)
a=a.replace("<text","")
print(18)
a=a.replace("<minor","")
print(19)
a=a.replace("<comment>","")
print(20)
a=a.replace("</comment>","")
print(21)
a=a.replace("REDIRECT","")
print(22)
a=a.replace("https","s")
print(23)
a=a.replace("http","")
print(24)
a=a.replace("<ip>","")
print(25)
a=a.replace("</ip>","")
print(26)
a=a.replace(" the ","A")
print(27)
a=a.replace(" of ","B")
print(28)
a=a.replace(" and ","D")
print(29)
a=a.replace(" in ","E")
print(30)
a=a.replace(" to ","F")
print(31)
a=a.replace(" a ","G")
print(32)
a=a.replace(" is ","H")
print(33)
a=a.replace(" for ","I")
print(34)
a=a.replace(" are ","J")
print(35)
a=a.replace(" was ","K")
print(36)
a=a.replace(" The ","L")
print(37)
a=a.replace(" as ","M")
print(38)
a=a.replace(" by ","N")
print(39)
a=a.replace(" with ","O")
print(40)
a=a.replace(" from ","P")
print(41)
a=a.replace(" that ","Q")
print(42)
a=a.replace(" on ","R")
print(43)
a=a.replace(" - ","S")
print(44)
a=a.replace(" or ","T")
print(45)
a=a.replace(" at ","U")
print(46)
a=a.replace(" an ","V")
print(47)
a=a.replace(" his ","W")
print(48)
a=a.replace(" have ","X")
print(49)
a=a.replace(" it ","Y")
print(50)
a=a.replace(" which ","Z")
print(51)
a=a.replace(" be ","1")
print(52)
a=a.replace(" (U.S. ","2")
print(53)
a=a.replace(" age ","3")
print(54)
a=a.replace(" he ","4")
print(55)
a=a.replace(" has ","5")
print(56)
a=a.replace(" were ","6")
print(57)
a=a.replace(" not ","7")
print(58)
a=a.replace(" also ","8")
print(59)
a=a.replace(" who ","9")
print(60)
a=a.replace(" had ","!")
print(61)
a=a.replace(" this ","@")
print(62)
a=a.replace(" but ","#")
print(63)
a=a.replace(" = ","$")
print(64)
a=a.replace(" | ","%")
print(65)
a=a.replace(" their ","^")
print(66)
a=a.replace(" there ","&")
print(67)
a=a.replace(" In ","*")
print(68)
a=a.replace(" under ","(")
print(69)
a=a.replace(" one ",")")
print(70)
a=a.replace(" more ","+")
print(71)
a=a.replace(" population ","~")
print(72)
a=a.replace(" its ","`")
print(73)
b=open("a","w", encoding='utf-8')
b.write(a)
b.close()
